task1
ilnurshug/SoftwareDesign pull request #1
Opened 2016-09-13 09:14 UTC by ilnurshug

2016-09-19 17:52 UTC, yurii-litvinov commented on README.md
> -# SoftwareDesign
ещё нужно что-нибудь, что помогло бы это собрать --- файл с правилами сборки для какой-нить билд-системы, проектные файлы среды разработки и т.д.

2016-09-19 17:53 UTC, yurii-litvinov commented on shell/src/main/java/adaptor/ANTLRParserAdaptor.java
> +public class ANTLRParserAdaptor {
нужны комментарии к каждому классу и каждому public-методу

2016-09-19 17:56 UTC, yurii-litvinov commented on shell/src/main/java/adaptor/SyntaxErrorListener.java
> +        Logger.log("line "+line+":"+charPositionInLine+" at "+offendingSymbol+": "+msg);
"+" обычно отделяется пробелами. а тут лучше вообще использовать логгер, поддерживающий запись в виде "line {}:{} at {}: {}"

2016-09-19 17:57 UTC, yurii-litvinov commented on shell/src/main/java/commands/Assignment.java
> + */
о, комментарий :) его лучше в формате JavaDoc, можно однострочный:

    /** Set variable value in environment */

2016-09-19 18:04 UTC, yurii-litvinov requested changes
диаграмма, конечно, лучше, чем ничего, но на неё неплохо бы добавить, кто кого содержит и использует. и надо больше комментариев в коде

2016-09-20 20:30 UTC, ilnurshug commented
Внес все необходимые изменения:
1) комментарии
2) диаграмма
3) инструкция по сборке
4) немного изменил архитектуру

2016-09-24 20:12 UTC, yurii-litvinov commented on README.md
> +	7. mark gen folder (contains ANTLR-generted lexer and parser) as Generated Sources Root
всё равно неудобно (ну или я что-то не так делаю). собрать мавеном из коробки не получается, потому что парсер надо сгенерить вручную из IDEA, а собрать идеей из коробки не получается, потому что проектных файлов нет, соответственно, нет и зависимостей. мне пришлось вручную добавить зависимые либы в проект в IDEA, чтобы собиралось. имеет смысл следать полный билд из мавена (попользовать http://www.antlr.org/api/maven-plugin/latest/usage.html) и/или выложить проектные файлы от IDEA.

2016-09-24 20:15 UTC, yurii-litvinov commented on shell/src/main/java/adaptor/ANTLRParserAdaptor.java
> +    /**
нужно ещё комментарий summary:

    /** Parses tree.
     * @ param ...
     * @return ...
     */

Так оно будет показываться в сгенерённых доках в summary, а так --- только в деталях

2016-09-24 21:01 UTC, yurii-litvinov commented on shell/src/main/java/commands/Command.java
> +    static Logger logger;
Макконнелл (ну, и не только он) не одобряет поля с пакетной видимостью, даже статические.

2016-09-24 21:04 UTC, yurii-litvinov requested changes
почти всё хорошо, но доделайте всё-таки систему сборки, пожалуйста

2016-09-24 22:11 UTC, ilnurshug commented on README.md
> +	7. mark gen folder (contains ANTLR-generted lexer and parser) as Generated Sources Root
Добавил файл shell.iml
Этого должно хватить для того чтобы удачно воспроизвести последовательность действий по сборке проекта.

2016-09-24 22:11 UTC, ilnurshug commented
Внес требуемые изменения

2016-09-24 23:24 UTC, yurii-litvinov commented on shell/src/main/java/commands/Command.java
> +    protected Logger logger;
protected-поля тоже плохо, к тому же они ещё и влекут пакетную видимость.

2016-09-24 23:25 UTC, yurii-litvinov approved these changes
теперь вроде всё ок, и собралось с ходу

2016-09-24 23:25 UTC, merged